// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const PLACEHOLDER_SUPABASE_URL = "https://placeholder.supabase.co";
const PLACEHOLDER_SERVICE_ROLE_KEY = "placeholder-key";

const MISSING_ADMIN_ENV_MESSAGE =
  "[Supabase Admin] Missing required server environment configuration. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.";

function isProductionRuntime(): boolean {
  return process.env.NODE_ENV === "production";
}

function isUsableSupabaseUrl(url: string | undefined): url is string {
  const value = url?.trim();
  if (!value) return false;
  if (value === PLACEHOLDER_SUPABASE_URL) return false;
  if (value.includes("placeholder")) return false;
  return true;
}

function isUsableServiceRoleKey(key: string | undefined): key is string {
  const value = key?.trim();
  if (!value) return false;
  if (value === PLACEHOLDER_SERVICE_ROLE_KEY) return false;
  if (value.includes("placeholder")) return false;
  return true;
}

/** Resolves admin credentials; throws in production when required env is missing or placeholder. */
export function resolveSupabaseAdminEnv(): {
  supabaseUrl: string;
  serviceRoleKey: string;
} {
  const rawUrl = process.env.SUPABASE_URL;
  const rawKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const configured = isUsableSupabaseUrl(rawUrl) && isUsableServiceRoleKey(rawKey);

  if (!configured) {
    if (isProductionRuntime()) {
      throw new Error(MISSING_ADMIN_ENV_MESSAGE);
    }
    console.warn(
      "[Supabase Admin] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not configured. Running in unconfigured mode.",
    );
    return {
      supabaseUrl: rawUrl?.trim() || PLACEHOLDER_SUPABASE_URL,
      serviceRoleKey: rawKey?.trim() || PLACEHOLDER_SERVICE_ROLE_KEY,
    };
  }

  return {
    supabaseUrl: rawUrl.trim(),
    serviceRoleKey: rawKey.trim(),
  };
}

function createSupabaseAdminClient() {
  const { supabaseUrl, serviceRoleKey } = resolveSupabaseAdminEnv();

  return createClient<Database>(supabaseUrl, serviceRoleKey, {
    global: {
      fetch: createSupabaseFetch(serviceRoleKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

/** Clears the lazy singleton so tests can re-resolve env. Test-only. */
export function resetSupabaseAdminClientForTests(): void {
  _supabaseAdmin = undefined;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/platform/database/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
