/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAiActivityIdeasRouteImport } from './routes/_authenticated/ai-activity-ideas'
import { Route as AuthenticatedAiEnrichmentRouteImport } from './routes/_authenticated/ai-enrichment'
import { Route as AuthenticatedAiLessonPlanRouteImport } from './routes/_authenticated/ai-lesson-plan'
import { Route as AuthenticatedAiQuizRouteImport } from './routes/_authenticated/ai-quiz'
import { Route as AuthenticatedAiWorksheetRouteImport } from './routes/_authenticated/ai-worksheet'
import { Route as AuthenticatedCorrectionsRouteImport } from './routes/_authenticated/corrections'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedCurriculumManagementRouteImport } from './routes/_authenticated/curriculum-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGoogleSheetsRouteImport } from './routes/_authenticated/google-sheets'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiActivityIdeasRoute =
  AuthenticatedAiActivityIdeasRouteImport.update({
    id: '/ai-activity-ideas',
    path: '/ai-activity-ideas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiEnrichmentRoute =
  AuthenticatedAiEnrichmentRouteImport.update({
    id: '/ai-enrichment',
    path: '/ai-enrichment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiLessonPlanRoute =
  AuthenticatedAiLessonPlanRouteImport.update({
    id: '/ai-lesson-plan',
    path: '/ai-lesson-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiQuizRoute = AuthenticatedAiQuizRouteImport.update({
  id: '/ai-quiz',
  path: '/ai-quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiWorksheetRoute =
  AuthenticatedAiWorksheetRouteImport.update({
    id: '/ai-worksheet',
    path: '/ai-worksheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorrectionsRoute =
  AuthenticatedCorrectionsRouteImport.update({
    id: '/corrections',
    path: '/corrections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumManagementRoute =
  AuthenticatedCurriculumManagementRouteImport.update({
    id: '/curriculum-management',
    path: '/curriculum-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoogleSheetsRoute =
  AuthenticatedGoogleSheetsRouteImport.update({
    id: '/google-sheets',
    path: '/google-sheets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AuthenticatedAiRoute
  '/ai-activity-ideas': typeof AuthenticatedAiActivityIdeasRoute
  '/ai-enrichment': typeof AuthenticatedAiEnrichmentRoute
  '/ai-lesson-plan': typeof AuthenticatedAiLessonPlanRoute
  '/ai-quiz': typeof AuthenticatedAiQuizRoute
  '/ai-worksheet': typeof AuthenticatedAiWorksheetRoute
  '/corrections': typeof AuthenticatedCorrectionsRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/curriculum-management': typeof AuthenticatedCurriculumManagementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/google-sheets': typeof AuthenticatedGoogleSheetsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AuthenticatedAiRoute
  '/ai-activity-ideas': typeof AuthenticatedAiActivityIdeasRoute
  '/ai-enrichment': typeof AuthenticatedAiEnrichmentRoute
  '/ai-lesson-plan': typeof AuthenticatedAiLessonPlanRoute
  '/ai-quiz': typeof AuthenticatedAiQuizRoute
  '/ai-worksheet': typeof AuthenticatedAiWorksheetRoute
  '/corrections': typeof AuthenticatedCorrectionsRoute
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/curriculum-management': typeof AuthenticatedCurriculumManagementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/google-sheets': typeof AuthenticatedGoogleSheetsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/ai-activity-ideas': typeof AuthenticatedAiActivityIdeasRoute
  '/_authenticated/ai-enrichment': typeof AuthenticatedAiEnrichmentRoute
  '/_authenticated/ai-lesson-plan': typeof AuthenticatedAiLessonPlanRoute
  '/_authenticated/ai-quiz': typeof AuthenticatedAiQuizRoute
  '/_authenticated/ai-worksheet': typeof AuthenticatedAiWorksheetRoute
  '/_authenticated/corrections': typeof AuthenticatedCorrectionsRoute
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/curriculum-management': typeof AuthenticatedCurriculumManagementRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/google-sheets': typeof AuthenticatedGoogleSheetsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai'
    | '/ai-activity-ideas'
    | '/ai-enrichment'
    | '/ai-lesson-plan'
    | '/ai-quiz'
    | '/ai-worksheet'
    | '/corrections'
    | '/curriculum'
    | '/curriculum-management'
    | '/dashboard'
    | '/google-sheets'
    | '/notifications'
    | '/planner'
    | '/reports'
    | '/settings'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/ai'
    | '/ai-activity-ideas'
    | '/ai-enrichment'
    | '/ai-lesson-plan'
    | '/ai-quiz'
    | '/ai-worksheet'
    | '/corrections'
    | '/curriculum'
    | '/curriculum-management'
    | '/dashboard'
    | '/google-sheets'
    | '/notifications'
    | '/planner'
    | '/reports'
    | '/settings'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/ai'
    | '/_authenticated/ai-activity-ideas'
    | '/_authenticated/ai-enrichment'
    | '/_authenticated/ai-lesson-plan'
    | '/_authenticated/ai-quiz'
    | '/_authenticated/ai-worksheet'
    | '/_authenticated/corrections'
    | '/_authenticated/curriculum'
    | '/_authenticated/curriculum-management'
    | '/_authenticated/dashboard'
    | '/_authenticated/google-sheets'
    | '/_authenticated/notifications'
    | '/_authenticated/planner'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-activity-ideas': {
      id: '/_authenticated/ai-activity-ideas'
      path: '/ai-activity-ideas'
      fullPath: '/ai-activity-ideas'
      preLoaderRoute: typeof AuthenticatedAiActivityIdeasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-enrichment': {
      id: '/_authenticated/ai-enrichment'
      path: '/ai-enrichment'
      fullPath: '/ai-enrichment'
      preLoaderRoute: typeof AuthenticatedAiEnrichmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-lesson-plan': {
      id: '/_authenticated/ai-lesson-plan'
      path: '/ai-lesson-plan'
      fullPath: '/ai-lesson-plan'
      preLoaderRoute: typeof AuthenticatedAiLessonPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-quiz': {
      id: '/_authenticated/ai-quiz'
      path: '/ai-quiz'
      fullPath: '/ai-quiz'
      preLoaderRoute: typeof AuthenticatedAiQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-worksheet': {
      id: '/_authenticated/ai-worksheet'
      path: '/ai-worksheet'
      fullPath: '/ai-worksheet'
      preLoaderRoute: typeof AuthenticatedAiWorksheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corrections': {
      id: '/_authenticated/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof AuthenticatedCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum-management': {
      id: '/_authenticated/curriculum-management'
      path: '/curriculum-management'
      fullPath: '/curriculum-management'
      preLoaderRoute: typeof AuthenticatedCurriculumManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google-sheets': {
      id: '/_authenticated/google-sheets'
      path: '/google-sheets'
      fullPath: '/google-sheets'
      preLoaderRoute: typeof AuthenticatedGoogleSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAiActivityIdeasRoute: typeof AuthenticatedAiActivityIdeasRoute
  AuthenticatedAiEnrichmentRoute: typeof AuthenticatedAiEnrichmentRoute
  AuthenticatedAiLessonPlanRoute: typeof AuthenticatedAiLessonPlanRoute
  AuthenticatedAiQuizRoute: typeof AuthenticatedAiQuizRoute
  AuthenticatedAiWorksheetRoute: typeof AuthenticatedAiWorksheetRoute
  AuthenticatedCorrectionsRoute: typeof AuthenticatedCorrectionsRoute
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedCurriculumManagementRoute: typeof AuthenticatedCurriculumManagementRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoogleSheetsRoute: typeof AuthenticatedGoogleSheetsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAiActivityIdeasRoute: AuthenticatedAiActivityIdeasRoute,
  AuthenticatedAiEnrichmentRoute: AuthenticatedAiEnrichmentRoute,
  AuthenticatedAiLessonPlanRoute: AuthenticatedAiLessonPlanRoute,
  AuthenticatedAiQuizRoute: AuthenticatedAiQuizRoute,
  AuthenticatedAiWorksheetRoute: AuthenticatedAiWorksheetRoute,
  AuthenticatedCorrectionsRoute: AuthenticatedCorrectionsRoute,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedCurriculumManagementRoute:
    AuthenticatedCurriculumManagementRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoogleSheetsRoute: AuthenticatedGoogleSheetsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
